# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7fc6c6029badca12b435ed097e7c378700544b0803a9ba1430aaba1bbc863ac89e23bbee715e9cc46dc5edd9e9ae1fab8a7c462a4b09a4c0fd6c2c95a2f4c0b

test:
  secret_key_base: f52cd608ad49624b3c31d15a9978aa1bc25770d68ce6223e4ca89435e1d3cfd5187a70a84811d073b9f41c56379cbcaceea4741881f9ffa3478b65653e4606c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
